2019-11-27 14:44:41 [twisted] CRITICAL: Unhandled error in Deferred:
2019-11-27 14:44:41 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs': 'phantomjs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 86, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/scrapy/utils/misc.py", line 146, in create_instance
    return objcls(*args, **kwargs)
  File "/Users/chumu/Desktop/myspider/Project/15-scrapy/num5_qidian/num5_qidian/mymiddles.py", line 10, in __init__
    self.driver = webdriver.PhantomJS()
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/Users/chumu/PycharmProjects/test/venv/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 

